# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.3 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================




prefix = /usr/local
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
INSTALL = /usr/bin/install -c
EXEEXT = 
WINDRES = 
SETFILE = 
STRIP = strip
NM = nm
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_DIR = $(INSTALL) -d
BK_DEPS = /home/leonti/proba/timelogger/trunk/bk-deps
srcdir = .
bindir = ${exec_prefix}/bin
datadir = ${datarootdir}
LIBS = 
LDFLAGS_GUI = 
CXX = g++
CXXFLAGS =  -I/opt/wx/2.8/lib/wx/include/gtk2-unicode-release-2.8 -I/opt/wx/2.8/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread
CPPFLAGS = 
LDFLAGS =  -L/opt/wx/2.8/lib -pthread   -L/usr/lib64   -lwx_gtk2u-2.8 

### Variables: ###

DESTDIR = 
TIMELOGGER_CXXFLAGS = -I/usr/include/mysql -I/usr/local/include/mysql++ -Wall \
	$(CPPFLAGS) $(CXXFLAGS)
TIMELOGGER_OBJECTS =  \
	$(__timelogger___win32rc) \
	timelogger_db_set_panel.o \
	timelogger_prog_set_panel.o \
	timelogger_login.o \
	timelogger_settings.o \
	timelogger_time_loggerApp.o \
	timelogger_time_loggerMain.o \
	timelogger_wx_std.o

### Conditionally set variables: ###

#CXXC = $(CXX)
CXXC = $(BK_DEPS) $(CXX)
__timelogger___mac_setfilecmd = @true
#__timelogger___mac_setfilecmd = \
#	$(SETFILE) -t APPL timelogger$(EXEEXT)
COND_PLATFORM_OS2_1___timelogger___os2_emxbindcmd = $(NM) timelogger$(EXEEXT) \
	| if grep -q pmwin.763 ; then emxbind -ep timelogger$(EXEEXT) ; fi
#__timelogger___os2_emxbindcmd = $(COND_PLATFORM_OS2_1___timelogger___os2_emxbindcmd)
#__timelogger___win32rc = timelogger_resource_rc.o

### Targets: ###

all: timelogger$(EXEEXT)

install: all install_timelogger
	$(INSTALL_DIR) $(DESTDIR)$(datadir)
	for f in locale/pl/LC_MESSAGES/timelogger.mo locale/es/LC_MESSAGES/timelogger.mo locale/ru/LC_MESSAGES/timelogger.mo locale/pt/LC_MESSAGES/timelogger.mo; do \
	if test ! -d $(DESTDIR)$(datadir)/`dirname $$f` ; then \
	$(INSTALL_DIR) $(DESTDIR)$(datadir)/`dirname $$f`; \
	fi; \
	$(INSTALL_DATA) share/$$f $(DESTDIR)$(datadir)/$$f; \
	done

uninstall: uninstall_timelogger
	for f in locale/pl/LC_MESSAGES/timelogger.mo locale/es/LC_MESSAGES/timelogger.mo locale/ru/LC_MESSAGES/timelogger.mo locale/pt/LC_MESSAGES/timelogger.mo; do \
	rm -f $(DESTDIR)$(datadir)/$$f; \
	done

install-strip: install
	$(STRIP) $(DESTDIR)$(bindir)/timelogger$(EXEEXT)

clean: 
	rm -rf ./.deps ./.pch
	rm -f ./*.o
	rm -f timelogger$(EXEEXT)

distclean: clean
	rm -f config.cache config.log config.status bk-deps bk-make-pch shared-ld-sh Makefile

timelogger$(EXEEXT): $(TIMELOGGER_OBJECTS) $(__timelogger___win32rc)
	$(CXX) -o $@ $(TIMELOGGER_OBJECTS) $(LDFLAGS)  $(LDFLAGS_GUI)  $(LIBS) -lmysqlpp -lmysqlclient
	
	$(__timelogger___mac_setfilecmd)
	$(__timelogger___os2_emxbindcmd)

install_timelogger: 
	$(INSTALL_DIR) $(DESTDIR)$(bindir)
	$(INSTALL_PROGRAM) timelogger$(EXEEXT) $(DESTDIR)$(bindir)

uninstall_timelogger: 
	rm -f $(DESTDIR)$(bindir)/timelogger$(EXEEXT)

timelogger_resource_rc.o: $(srcdir)/src/res/resource.rc
	$(WINDRES) -i$< -o$@  --include-dir /usr/include/mysql --include-dir /usr/local/include/mysql++

timelogger_db_set_panel.o: $(srcdir)/src/db_set_panel.cpp
	$(CXXC) -c -o $@ $(TIMELOGGER_CXXFLAGS) $(srcdir)/src/db_set_panel.cpp

timelogger_prog_set_panel.o: $(srcdir)/src/prog_set_panel.cpp
	$(CXXC) -c -o $@ $(TIMELOGGER_CXXFLAGS) $(srcdir)/src/prog_set_panel.cpp

timelogger_login.o: $(srcdir)/src/login.cpp
	$(CXXC) -c -o $@ $(TIMELOGGER_CXXFLAGS) $(srcdir)/src/login.cpp

timelogger_settings.o: $(srcdir)/src/settings.cpp
	$(CXXC) -c -o $@ $(TIMELOGGER_CXXFLAGS) $(srcdir)/src/settings.cpp

timelogger_time_loggerApp.o: $(srcdir)/src/time_loggerApp.cpp
	$(CXXC) -c -o $@ $(TIMELOGGER_CXXFLAGS) $(srcdir)/src/time_loggerApp.cpp

timelogger_time_loggerMain.o: $(srcdir)/src/time_loggerMain.cpp
	$(CXXC) -c -o $@ $(TIMELOGGER_CXXFLAGS) $(srcdir)/src/time_loggerMain.cpp

timelogger_wx_std.o: $(srcdir)/src/wx_std.cpp
	$(CXXC) -c -o $@ $(TIMELOGGER_CXXFLAGS) $(srcdir)/src/wx_std.cpp


# Include dependency info, if present:
-include .deps/*.d

.PHONY: all install uninstall clean distclean install_timelogger uninstall_timelogger
